local t = tuple(list {_to_null(1, 2, 3, nil)})
assert(bool((len(t) == 4)))
assert(bool((t[_to_null(0)] == 1)))
assert(bool((t[_to_null(1)] == 2)))
assert(bool((t[_to_null(2)] == 3)))
assert(bool((t[_to_null(3)] == nil)))
t = tuple(list {_to_null(1, "a", "z", "pi", "a", "c", "c", nil)})
assert(bool((t.count(1) == 1)))
assert(bool((t.count("a") == 2)))
assert(bool((t.count("b") == 0)))
assert(bool((t.count("c") == 2)))
assert(bool((t.count(nil) == 1)))
t = tuple(list {_to_null(1, "a", "z", "pi", "a", "c", "c")})
assert(bool((t.index("a") == 1)))
assert(bool((t.index("a", 0) == 1)))
assert(bool((t.index("a", 1) == 1)))
assert(bool((t.index("a", 2) == 4)))
assert(bool((t.index("a", 3) == 4)))
assert(bool((t.index("a", 4) == 4)))
assert(bool((t.index("a", 1, 4) == 1)))
assert(bool((t.index("a", 2, 5) == 4)))
return {
    t = t,
}
