dofile('./polyfill/pypolyfill.lua')
local a = (bit.blshift(1, 2))
assert((a == 4))
a = (bit.brshift(1, 3))
assert((a == 0))
local b = (bit.band(2, 7))
assert((b == 2))
local c = (bit.bor(2, 7))
assert((c == 7))
local d = bit.bnot(1)
assert((d == (-2)))
local e = (bit.bxor(3, 3))
assert((e == 0))
