dofile('./polyfill/pypolyfill.lua')
local t = tuple(list {_null(1, 2, 3)})
assert((len(t) == 3))
assert((t[0] == 1))
assert((t[1] == 2))
assert((t[2] == 3))
t = tuple(list {_null(1, "a", "z", "pi", "a", "c", "c")})
assert((t.count(1) == 1))
assert((t.count("a") == 2))
assert((t.count("b") == 0))
assert((t.count("c") == 2))
t = tuple(list {_null(1, "a", "z", "pi", "a", "c", "c")})
assert((t.index("a") == 1))
assert((t.index("a", 0) == 1))
assert((t.index("a", 1) == 1))
assert((t.index("a", 2) == 4))
assert((t.index("a", 3) == 4))
assert((t.index("a", 4) == 4))
assert((t.index("a", 1, 4) == 1))
assert((t.index("a", 2, 5) == 4))
